name = "FinancialSymbology"
uuid = "9d391c44-9e33-4973-a6cd-c9dd346bb47a"
authors = ["Rob <robfoxsimms@gmail.com> and contributors"]
version = "0.3.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
Documenter = "0.27"
HTTP = "0.9"
JSON = "0.21"
StructArrays = "0.5, 0.6"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
