name = "FinancialSymbology"
uuid = "9d391c44-9e33-4973-a6cd-c9dd346bb47a"
authors = ["Rob <robfoxsimms@gmail.com> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21"
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
